markdown: kramdown
url: ""
baseurl: ""
title: Javier Manobanda
description: Mechatronic | Software Developer
site-image: /assets/images/imagenSite.png
site-keywords: "Site, Template, Theme"
favicon-url: null
heroimage: /assets/images/Portada.svg
email: javierdeveloper27@gmail.com
facebook_username:
twitter_username: JaviM_iot
instagram_username: javim_iot
linkedin_username: javimiot
github_username: JaviMiot
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:
google-analytics:
disqus-shortname:
author-name: Javier Manobanda
author-image: /assets/images/FotoV2.jpg
author-about: >-
  Mechatronic engineer. Focused on STEM (Science, Technology, Engineering, and Mathematics). Entrepreneur in the area of technology and design of digital products, with experience in software development and Iot. Currently in constant learning to improve myself as a full stack developer.
author-url: "https://github.com/JaviMiot"
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: "blog/:title"
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
